### ISSUE TITLE
The folder called "property" is not included in the pip package.

### ISSUE THREAD

**Issue by curious-cat-163** [joeyagreco/hacker-news#1]
I installed the 0.1.0 package:

```
% pip freeze
certifi==2024.2.2
charset-normalizer==3.3.2
hn-sdk==0.1.0
idna==3.7
requests==2.31.0
urllib3==2.2.1
```

However, when I run the example, I get a KeyError about a key HACKER_NEWS_API. I traced it down to the install that the package did in my virtualenv and there is no folder named "property" as referred to the following line:

https://github.com/joeyagreco/hacker-news/blob/51afe17f426b928464f515de9dce84cbb35403c0/hn_sdk/util/ConfigReader.py#L19

I don't understand precisely how you have bundled the package, but somehow that folder does not get downloaded with 0.1.0

**Comment by joeyagreco** [comment]
Thank you for finding this bug!

This has been fixed in [v0.1.1](https://github.com/joeyagreco/hacker-news/releases/tag/v0.1.1)

Please run `pip install --upgrade hn-sdk` and this should be fixed
